### ISSUE TITLE
What happens when just run it through a noise filter like this?

### ISSUE THREAD

**Issue by beyondarmonia** [VinAIResearch/Anti-DreamBooth#1]
https://github.com/lllyasviel/AdverseCleaner

**Comment by hao-pt** [comment]
Thank you for introducing us to this tool. We're pleased to share the results with you. As can be seen in the image below, our defense method remains robust to filtered-noise examples, even when the level of noise in input images is reduced.

![filtered_noise_results](https://user-images.githubusercontent.com/31931630/228137346-724435af-27c0-438c-a814-52d642e82819.png)
