### ISSUE TITLE
Bugs.

### ISSUE THREAD

**Issue by Bugcreatorfool** [VinAIResearch/Anti-DreamBooth#10]
When I re-run anti-dreambooth code in your settings, I meet errors below.

1. stable-diffusion/stable-diffusion-2-1-base does not appear to have a file named config.json.
2. subprocess.CalledProcessError: Command'... ...' returned non-zero exit status 1.

As I have no idea, could you please help me or fix the bugs of code.

**Comment by hao-pt** [comment]
Have you downloaded pretrained `stable-diffusion-2-1-base` and put it in `stable-diffusion`? If not, please download it first and then run our script. Thanks!

**Comment by Bugcreatorfool** [comment]
It's alright now, thanks. 
Another of my concerns is not comparing the quality of the generated images with the same $l_{p}$ scale of random perturbation.

**Comment by riolys** [comment]
> When I re-run anti-dreambooth code in your settings, I meet errors below.
> 
> 1. stable-diffusion/stable-diffusion-2-1-base does not appear to have a file named config.json.
> 2. subprocess.CalledProcessError: Command'... ...' returned non-zero exit status 1.
> 
> As I have no idea, could you please help me or fix the bugs of code.

may i know how to solve the question 1?
