### ISSUE TITLE
Questions about full split sets of each dataset.

### ISSUE THREAD

**Issue by KululuMi** [VinAIResearch/Anti-DreamBooth#12]
Hello authors, Anti-DreamBooth is very interesting, and I want to follow your this work! However, I met some trouble with data, can you provide me with the full split sets of each dataset?

Thanks a lot.

**Comment by thuanz123** [comment]
Hi @KululuMi, thanks for your kind words. We will update information about the dataset soon. In the mean time, you can access to the full data split at [here](https://drive.google.com/drive/folders/1JX4IM6VMkkv4rER99atS4x4VGnoRNByV?usp=sharing)

**Comment by KululuMi** [comment]
Thanks a lot!
