### ISSUE TITLE
Hello，I have a question

### ISSUE THREAD

**Issue by long280** [VinAIResearch/Anti-DreamBooth#13]
Excuse me, I want to try the running effect of the code. Is there any requirement for the graphics card device?

**Comment by thuanz123** [comment]
1. To use the code directly, you would need a GPU with at least 32GB of memory. Our experiments are typically conducted using a 40GB A100 GPU.
2. Alternatively, you can refer to [this tutorial](https://huggingface.co/docs/diffusers/training/dreambooth) and make some minor changes to our code to train on a GPU with lower VRAM (as low as 12GB).

**Comment by long280** [comment]
Ok, thank you very much
