### ISSUE TITLE
Questions about quantitative evaluation metrics

### ISSUE THREAD

**Issue by KululuMi** [VinAIResearch/Anti-DreamBooth#14]
Hello, authors~ thanks for your help to provide the split dataset. However, I met some trouble when tried to reproduce quantitative evaluation metrics...Can you provide the code of quantitative evaluation metrics (Face Detection Failure Rate (FDFR) and Identity Score Matching (SM))? Thanks a lot!

**Comment by hao-pt** [comment]
FYI, evaluation code is updated. Feel free to reopen this issue in case you need further aid!
