### ISSUE TITLE
fail to generate adversial samples when running attack_aspl script

### ISSUE THREAD

**Issue by Bomingmiao** [VinAIResearch/Anti-DreamBooth#17]
![mmexport1701355394315](https://github.com/VinAIResearch/Anti-DreamBooth/assets/110110792/bc2e00be-b7bb-45b2-90a1-ae8c7434ffb2)
there is no ipynb.checkpoints in the data given.Why there is an Isdirectoryerror?

**Comment by thuanz123** [comment]
maybe because the file is hidden, since any file starts with "." will be hidden by default. You can use command in the terminal to remove it "rm /root/autodl-fs/anti/data/n000050/set_B/.ipynb_checkpoints"

**Comment by Bomingmiao** [comment]
> maybe because the file is hidden, since any file starts with "." will be hidden by default. You can use command in the terminal to remove it "rm /root/autodl-fs/anti/data/n000050/set_B/.ipynb_checkpoints"

thank you so much
