### ISSUE TITLE
can you provide some perturbed images to test?

### ISSUE THREAD

**Issue by ninjasaid2k** [VinAIResearch/Anti-DreamBooth#2]
can you provide some perturbed images to test?

**Comment by ninjasaid2k** [comment]
is it possible that the noise can simply be removed with a photoshop filter?
![b3p6tr9q3mqa1](https://user-images.githubusercontent.com/99513716/228395272-a33a954a-5e9e-4e81-bf38-9b9d3fa43951.png)

**Comment by ninjasaid2k** [comment]
I'm seeing some examples of denoising and Photoshop blurring might possibly 
![RDT_20230328_1822353940772148723359913](https://user-images.githubusercontent.com/99513716/228402394-2c29a45f-55df-43f0-83e4-58792d46e54a.jpg)
remove it

**Comment by hao-pt** [comment]
FYI, we are pleased to share some with you: https://drive.google.com/drive/folders/1_JpCYjfAkfEAyMc0e6OWVkI0no-WXOZN?usp=share_link
