### ISSUE TITLE
What data should be put in data/class-person?

### ISSUE THREAD

**Issue by Crazygay12138** [VinAIResearch/Anti-DreamBooth#23]
It seems that this repository does not provide the data in data/class-person.

**Comment by Luvata** [comment]
images in data/class-person is intentionally omitted to reduce repo size. It's generated automatically when running train_dreambooth.py - [this part on generate prior preservation data](https://github.com/VinAIResearch/Anti-DreamBooth/blob/main/train_dreambooth.py#L617)
