### ISSUE TITLE
can it be used on specific pictures?

### ISSUE THREAD

**Issue by alidcast** [VinAIResearch/Anti-DreamBooth#4]
looks like its meant for training a model and generating perturbed images

What if you have a real image and want to safeguard it while keeping visual unchanged? In other words, can infer be be used on an image rather than a prompt?

**Comment by hao-pt** [comment]
Hi, I'm not certain I understand what you mean. Are you asking if the model can be conditioned with an image instead of an input prompt? If that's the case, I'm afraid that is beyond the scope of what we can address.

**Comment by thuanz123** [comment]
We still do not understand what you mean by "safeguard that image from being used"? Being used for what? And by the way our project is only to protect the images from being used for training DreamBooth model. If you haven't know what DreamBooth is then please refer to this [link](https://dreambooth.github.io/) for an overall view or read the [paper](https://arxiv.org/abs/2208.12242) directly. We close this issue for now as we think what you asked is not related to DreamBooth and our work. Feel free to re-open it

**Comment by thuanz123** [comment]
Yes, you understand our motivation correctly and we are deeply sorry for our misunderstadning. To answer your question, after running our algorithms, by default the perturbed images wil be saved at "outputs/{algorithm_name}/{instance_dataset_name}_ADVERSARIAL/noise-ckpt/50". 

For example, if you run the following script without any changes:

```
bash scripts/attack_with_aspl.sh
``` 

the perrturbed images will be stored at "outputs/ASPL/n000050_ADVERSARIAL/noise-ckpt/50""
